services:
  redis-studies:
    image: redis:latest
    container_name: my-redis
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
